exports.mappingFile = {
	name:["name"],
	emailId:["emailId"],
	batch:["batch"],
	course:["course"],
	branch:["branch"],
	rollNumber:["rollNumber"],
	certificate:["certificate"],
	
	fathersName:["fathersName"],
	nationality:["nationality"],
	aadhaarId:["aadhaarId"],
	passportNumber:["passportNumber"],
	dateOfBirth:["dateOfBirth"],
	joinedDate:["joinedDate"],
	phoneNumber:["phoneNumber"],
	address:["address"],
	pinCode:["pinCode"]
};
exports.aadharConfig = {
		response:{
			piName:1,
			piNameMatch:29,
			piEmail:6,
			piemailMatch:34,
			piPhone:5,
			piPhoneMatch:33,
			pidob:4,
			pidobMatch:32,
			pfa:17,
			pfaMatch:45
		},
		authenticate:true,
		format:{
			pi:{
				include:true,
				ms:"P",
				mv:60,
				name:true,
				dob:true,
				gender:false,
				phone:true,
				email:false
			},
			pfa:{
				include:true,
				ms:"P",
				mv:20,
				av:true
			},
			pa:{
				include:false
				
			}
		}
};
exports.url_template = 'https://<host>/<ver>/<ac>/<uid[0]>/<uid[1]>/<asalk>';
exports.currentAPIVersion = '1.6';   //current version of the Aadhaar Auth API, if API is updated then this constant should be changed

//txn :- transaction id for AUA, generated by AUA
//lk: -liscense key, assigned to the AUA. Available on Administration portal
//Lot :- G or P depending on whether to giv lat/long or postal code
//type :- PID type
//UDC :- Unique Device Code, should be unique for every device that requests this information (Alpha numeric string of max length 20)
//          [vendorcode][date of deployment][serial number]
//ci :- expiry date of the certificate, should be of the form YYYYMMDD
//      current certificate has expiration date of 16 Sept 2020, 20200916
//1.6
exports.public_config_attrs = {
    "asalk":"MG41KIrkk5moCkcO8w-2fc01-P7I5S-6X2-X7luVcDgZyOa2LXs3ELI",
    "host":"auth.uidai.gov.in",
    "ac":"public",
    "sa":"public",
    "tid":"public",
    "ver":"1.6",
    "txn": "AuthDemoClient:public",
    "lk": "MEaMX8fkRa6PqsqK6wGMrEXcXFl_oXHA-YuknI2uf0gKgZ80HaZgG3A",
    "pi": "y",
    "udc": "nodeclient1",
    "fdc": "NA",
    "idc": "NA",
    "pip": "NA",
    "lot": "P",
    "type":"X",
    "ci": 20200916
};
exports.basic_uses_attrs = {
		"bio": "n",
	    "otp": "n",
	    "pa": "n",
	    "pfa": "y",
	    "pi": "y",
	    "pin": "n"
};